# Supabase Project Configuration
# https://supabase.com/docs/guides/cli/config

[project]
name = "arabic-voice-agent"

[api]
enabled = true
port = 54321
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [""]
jwt_expiry = 3600

[auth.external.google]
enabled = true
# Configure client_id and client_secret in Supabase dashboard

[edge_functions]
# Edge Functions are DISABLED as requested
enabled = false
