name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Create empty .env file
        run: touch .env

      - name: Install dependencies
        run: flutter pub get

      - name: dart format
        run: dart format --set-exit-if-changed -l 120 .

      - name: flutter analyze
        run: flutter analyze --no-fatal-infos

      - name: flutter test
        run: flutter test

      - name: Android Build
        run: flutter pub get && flutter test && flutter build apk && flutter build appbundle
