#!/usr/bin/env bash
# Pull secrets from AWS Secrets Manager and populate local .env files.
#
# Usage:
#   scripts/pull-secrets.sh                     # prod Supabase, preview API keys (default)
#   scripts/pull-secrets.sh --local             # local Supabase (starts it if needed)
#   scripts/pull-secrets.sh <secret-id>         # custom secret for API keys, prod Supabase
#
# Supabase mode:
#   By default this writes web-api/.env pointing at the PROD Supabase project
#   (SUPABASE_URL/KEYS pulled from mishmish/prod/api). This avoids requiring
#   a local Supabase stack for day-to-day work.
#
#   Pass --local to use a local Supabase stack instead. That path delegates to
#   scripts/use-local-supabase.sh which also claims a cross-worktree lock.
#
# Prerequisites:
#   - AWS CLI configured (`aws sso login` or similar)
#   - jq installed

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REGION="${AWS_REGION:-us-west-2}"

# --- Parse args ---
MODE="prod"
API_SECRET_ID="mishmish/preview/api"
PROD_SECRET_ID="mishmish/prod/api"

if [[ "${1:-}" == "--local" ]]; then
  MODE="local"
elif [[ -n "${1:-}" ]]; then
  API_SECRET_ID="$1"
fi

if [[ "$MODE" == "local" ]]; then
  exec "$REPO_ROOT/scripts/use-local-supabase.sh"
fi

# --- Fetch API-keys secret (preview by default) ---
echo "Fetching API secrets from: $API_SECRET_ID"
API_SECRET_JSON=$(aws secretsmanager get-secret-value \
  --secret-id "$API_SECRET_ID" \
  --region "$REGION" \
  --query SecretString --output text)

api_val() { echo "$API_SECRET_JSON" | jq -r ".$1 // empty"; }

# --- Fetch prod Supabase creds ---
echo "Fetching Supabase prod creds from: $PROD_SECRET_ID"
PROD_SECRET_JSON=$(aws secretsmanager get-secret-value \
  --secret-id "$PROD_SECRET_ID" \
  --region "$REGION" \
  --query SecretString --output text)

prod_val() { echo "$PROD_SECRET_JSON" | jq -r ".$1 // empty"; }

SUPABASE_URL=$(prod_val SUPABASE_URL)
SUPABASE_SECRET_KEY=$(prod_val SUPABASE_SECRET_KEY)
SUPABASE_PUBLISHABLE_KEY=$(prod_val SUPABASE_PUBLISHABLE_KEY)

# --- web-api/.env ---
echo "Writing web-api/.env (Supabase: PROD) ..."
cat > "$REPO_ROOT/web-api/.env" <<EOF
# Auto-generated by scripts/pull-secrets.sh — do not commit.
# Supabase mode: PROD (remote project). Run scripts/use-local-supabase.sh to switch to local.

SUPABASE_MODE=prod
SUPABASE_URL=$SUPABASE_URL
SUPABASE_SECRET_KEY=$SUPABASE_SECRET_KEY
SUPABASE_PUBLISHABLE_KEY=$SUPABASE_PUBLISHABLE_KEY

# AI / Voice pipeline (from Secrets Manager)
OPENAI_API_KEY=$(api_val OPENAI_API_KEY)
ELEVEN_API_KEY=$(api_val ELEVEN_API_KEY)
SONIOX_API_KEY=$(api_val SONIOX_API_KEY)
GEMINI_API_KEY=$(api_val GEMINI_API_KEY)

# Local config
WEBHOOK_BASE_URL=http://localhost:8000
POSTHOG_API_KEY=phc_1ZBbhKOZcsCo52DvnYzl1ie38hPfPaLrUCxdymVhDIQ
POSTHOG_HOST=https://us.i.posthog.com
HOST=0.0.0.0
PORT=8000
EOF
chmod 600 "$REPO_ROOT/web-api/.env"
echo "  ✓ web-api/.env (PROD Supabase)"

# --- web-app/.env / admin-app/.env / supabase/.env ---
for pkg in web-app admin-app supabase; do
  if [[ ! -f "$REPO_ROOT/$pkg/.env" ]]; then
    cp "$REPO_ROOT/$pkg/.env.example" "$REPO_ROOT/$pkg/.env"
    echo "  ✓ $pkg/.env (copied from example)"
  fi
done

echo ""
echo "Done. web-api is pointed at PROD Supabase."
echo "Switch to local with: scripts/use-local-supabase.sh"
