#!/usr/bin/env bash
# Pull secrets from AWS Secrets Manager and populate local .env files.
#
# Usage:
#   scripts/pull-secrets.sh                     # uses mishmish/preview/api
#   scripts/pull-secrets.sh <secret-id>         # uses a specific secret name or ARN
#
# Prerequisites:
#   - AWS CLI configured with appropriate credentials (`aws sso login` or similar)
#   - jq installed
#
# What it does:
#   1. Fetches API secrets from AWS Secrets Manager
#   2. Writes web-api/.env with secrets + local Supabase defaults + static config
#   3. Copies web-app/.env.example → web-app/.env (no secrets needed)
#   4. Copies admin-app/.env.example → admin-app/.env (no secrets needed)
#   5. Ensures supabase/.env exists from its example (no SM secrets needed locally)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REGION="${AWS_REGION:-us-west-2}"

# --- Resolve secret ID ---
DEFAULT_SECRET="mishmish/preview/api"
SECRET_ID="${1:-$DEFAULT_SECRET}"

echo "Fetching secrets from: $SECRET_ID"
SECRET_JSON=$(aws secretsmanager get-secret-value \
  --secret-id "$SECRET_ID" \
  --region "$REGION" \
  --query SecretString --output text)

# Helper to extract a key from the secret JSON, returning empty string if missing
secret_val() {
  echo "$SECRET_JSON" | jq -r ".$1 // empty"
}

# --- web-api/.env ---
echo "Writing web-api/.env ..."
cat > "$REPO_ROOT/web-api/.env" <<EOF
# Auto-generated by scripts/pull-secrets.sh — do not commit.

# Supabase — using local defaults (override if pointing at a remote project)
SUPABASE_URL=http://localhost:54321
SUPABASE_SECRET_KEY=$(supabase -C "$REPO_ROOT" status --output json 2>/dev/null | jq -r '.SERVICE_ROLE_KEY // empty' || true)
SUPABASE_PUBLISHABLE_KEY=$(supabase -C "$REPO_ROOT" status --output json 2>/dev/null | jq -r '.ANON_KEY // empty' || true)

# AI / Voice pipeline (from Secrets Manager)
OPENAI_API_KEY=$(secret_val OPENAI_API_KEY)
ELEVEN_API_KEY=$(secret_val ELEVEN_API_KEY)
SONIOX_API_KEY=$(secret_val SONIOX_API_KEY)
GEMINI_API_KEY=$(secret_val GEMINI_API_KEY)

# Local config
WEBHOOK_BASE_URL=http://localhost:8000
POSTHOG_API_KEY=phc_1ZBbhKOZcsCo52DvnYzl1ie38hPfPaLrUCxdymVhDIQ
POSTHOG_HOST=https://us.i.posthog.com
HOST=0.0.0.0
PORT=8000
EOF
chmod 600 "$REPO_ROOT/web-api/.env"
echo "  ✓ web-api/.env"

# --- web-app/.env ---
if [[ ! -f "$REPO_ROOT/web-app/.env" ]]; then
  echo "Writing web-app/.env from example ..."
  cp "$REPO_ROOT/web-app/.env.example" "$REPO_ROOT/web-app/.env"
  echo "  ✓ web-app/.env (copied from .env.example)"
else
  echo "  – web-app/.env already exists, skipping"
fi

# --- admin-app/.env ---
if [[ ! -f "$REPO_ROOT/admin-app/.env" ]]; then
  echo "Writing admin-app/.env from example ..."
  cp "$REPO_ROOT/admin-app/.env.example" "$REPO_ROOT/admin-app/.env"
  echo "  ✓ admin-app/.env (copied from .env.example)"
else
  echo "  – admin-app/.env already exists, skipping"
fi

# --- supabase/.env ---
if [[ ! -f "$REPO_ROOT/supabase/.env" ]]; then
  echo "Writing supabase/.env from example ..."
  cp "$REPO_ROOT/supabase/.env.example" "$REPO_ROOT/supabase/.env"
  echo "  ✓ supabase/.env (copied from .env.example)"
else
  echo "  – supabase/.env already exists, skipping"
fi

echo ""
echo "Done. Secrets written to web-api/.env."
echo "Note: web-api/.env always gets overwritten. Other .env files are only created if missing."
