name: Deploy Supabase migrations

on:
  workflow_call:
    inputs:
      ref:
        description: Git ref to checkout
        required: true
        type: string

jobs:
  deploy:
    name: Push migrations & config
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: supabase/setup-cli@v1
        with:
          version: 2.65.5

      - name: Install dotenvx
        run: curl -sfS https://dotenvx.sh/install.sh | sh

      - name: Deploy to Supabase
        env:
          DOTENV_PRIVATE_KEY_PRODUCTION: ${{ secrets.DOTENV_PRIVATE_KEY_PRODUCTION }}
          SUPABASE_PROJECT_REF: ${{ vars.SUPABASE_PROJECT_REF }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_PERSONAL_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          dotenvx run -f supabase/.env.production -- sh -c 'supabase link --project-ref $SUPABASE_PROJECT_REF'
          dotenvx run -f supabase/.env.production -- sh -c 'supabase config push --yes'
          dotenvx run -f supabase/.env.production -- sh -c 'supabase db push --include-seed'
