name: Deploy LiveKit Agent

on:
  push:
    branches:
      - main
    paths:
      - "livekit-agent/**"
      - ".github/workflows/deploy-livekit-agent.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: livekit-agent

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy LiveKit Cloud Agent
        uses: livekit/deploy-action@main
        env:
          LIVEKIT_URL: ${{ vars.LIVEKIT_URL }}
          LIVEKIT_API_KEY: ${{ vars.LIVEKIT_API_KEY }}
          LIVEKIT_API_SECRET: ${{ secrets.LIVEKIT_API_SECRET }}
        with:
          WORKING_DIRECTORY: ./livekit-agent
          OPERATION: deploy

      - name: Notify deployment
        run: |
          echo "Agent deployed to LiveKit Cloud successfully!"
