name: Deploy Agent to LiveKit Cloud

on:
  push:
    branches:
      - main
    paths:
      - 'livekit-agent/**'
      - '.github/workflows/deploy-agent.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install LiveKit CLI
        run: |
          curl -sSL https://get.livekit.io/cli | bash

      - name: Deploy to LiveKit Cloud
        env:
          LIVEKIT_URL: ${{ secrets.LIVEKIT_URL }}
          LIVEKIT_API_KEY: ${{ secrets.LIVEKIT_API_KEY }}
          LIVEKIT_API_SECRET: ${{ secrets.LIVEKIT_API_SECRET }}
        working-directory: livekit-agent
        run: |
          lk deploy \
            --name arabic-voice-agent \
            --api-key $LIVEKIT_API_KEY \
            --api-secret $LIVEKIT_API_SECRET \
            --url $LIVEKIT_URL

      - name: Notify deployment
        run: |
          echo "Agent deployed to LiveKit Cloud successfully!"
