name: Deploy LiveKit Agent

on:
  push:
    branches:
      - main
    paths:
      - "livekit-agent/**"
      - ".github/workflows/deploy-livekit-agent.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: livekit-agent

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install LiveKit CLI
        run: |
          curl -sSL https://get.livekit.io/cli | bash
          echo "$HOME/.livekit" >> $GITHUB_PATH

      - name: Install dependencies
        run: task install

      - name: Deploy to LiveKit Cloud
        env:
          LIVEKIT_URL: ${{ vars.LIVEKIT_URL }}
          LIVEKIT_API_KEY: ${{ vars.LIVEKIT_API_KEY }}
          LIVEKIT_API_SECRET: ${{ secrets.LIVEKIT_API_SECRET }}
        run: task deploy

      - name: Notify deployment
        run: |
          echo "Agent deployed to LiveKit Cloud successfully!"
