name: Deploy LiveKit Agent

on:
  push:
    branches:
      - main
    paths:
      - 'livekit-agent/**'
      - '.github/workflows/deploy-livekit-agent.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: livekit-agent
        run: |
          pip install -r requirements.txt

      - name: Deploy to LiveKit Cloud
        env:
          LIVEKIT_URL: ${{ secrets.LIVEKIT_URL }}
          LIVEKIT_API_KEY: ${{ secrets.LIVEKIT_API_KEY }}
          LIVEKIT_API_SECRET: ${{ secrets.LIVEKIT_API_SECRET }}
        working-directory: livekit-agent
        run: |
          python -m livekit.agents.cli deploy

      - name: Notify deployment
        run: |
          echo "Agent deployed to LiveKit Cloud successfully!"
