name: 🛠 Android CI / Build & Release APK

on:
  push:
    branches: [ main ]
    tags:    [ 'v*.*.*' ]
    paths:
      - 'flutter-app/**'
      - '.github/workflows/flutter-app-deploy-dev.yml'

permissions:
  contents: write   # allow creating/updating Releases & uploading assets
  actions:  read    # allow pulling marketplace actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Cache pub deps
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: ☕️ Setup Java (Temurin 17)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: 🦋 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: 📥 Get dependencies
        run: flutter pub get

      - name: ✅ Run tests
        run: flutter test --coverage

#      - name: 🏗️ Build APKs
#        run: flutter build appbundle

#      - name: 📦 Prepare artifacts
#        run: |
#          mkdir -p artifacts
#          cp build/app/outputs/bundle/release/*.aab artifacts/

#      - name: 📤 Upload build artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: aab-builds
#          path: artifacts/*.apk
#          retention-days: 30

      # ─────────────── ONLY ON TAGS ───────────────
#      - name: 🏷️ Create or update Release
#        if: startsWith(github.ref, 'refs/tags/v')
#        uses: ncipollo/release-action@v1.16.0
#        with:
#          tag:       ${{ github.ref_name }}
#          name:      Release ${{ github.ref_name }}
#          artifacts: artifacts/*.apk
#          token:     ${{ secrets.GITHUB_TOKEN }}