name: Flutter Tests

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'apps/mobile/**'
      - '.github/workflows/test-mobile.yml'
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Install dependencies
        working-directory: apps/mobile
        run: flutter pub get

      - name: Run analyzer
        working-directory: apps/mobile
        run: flutter analyze

      - name: Run tests
        working-directory: apps/mobile
        run: flutter test

      - name: Build APK (Android)
        working-directory: apps/mobile
        run: flutter build apk --debug

      - name: Notify success
        run: |
          echo "Flutter tests passed successfully!"
